import type { Metadata, Viewport } from "next";
import { fontVariableClassName } from "@/app/fonts";
import { ELIJAH } from "@/lib/elijah";
import { PERSON_ID, SITE_URL, WEBSITE_ID, absoluteUrl } from "@/lib/site-url";
import { PUBLIC_ROUTES } from "@/lib/public-routes";
import { THEME_COLORS } from "@/lib/theme";
import "./globals.css";

const PAGE_TITLE = `${ELIJAH.name} | ${ELIJAH.role}`;
const PROFILE_URL = absoluteUrl(PUBLIC_ROUTES.about);
const GOOGLE_SITE_VERIFICATION = process.env.GOOGLE_SITE_VERIFICATION?.trim();
const BING_SITE_VERIFICATION = process.env.BING_SITE_VERIFICATION?.trim();
const SITE_VERIFICATION: Metadata["verification"] =
  GOOGLE_SITE_VERIFICATION || BING_SITE_VERIFICATION
    ? {
        ...(GOOGLE_SITE_VERIFICATION
          ? { google: GOOGLE_SITE_VERIFICATION }
          : {}),
        ...(BING_SITE_VERIFICATION
          ? { other: { "msvalidate.01": BING_SITE_VERIFICATION } }
          : {}),
      }
    : undefined;

// Site-wide structured data. Deliberately minimal: only the WebSite node and a
// Person *stub* carrying the stable @id. The full Person — address,
// alumni affiliation, expertise areas, sameAs — lives on /about, the one page
// that visibly renders those facts. Repeating it on every route would mark up
// information unrelated to the page a reader is looking at.
const SITE_JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": WEBSITE_ID,
      url: SITE_URL,
      name: ELIJAH.osName,
      description: ELIJAH.metadataDescription,
      inLanguage: "en",
      creator: { "@id": PERSON_ID },
      publisher: { "@id": PERSON_ID },
    },
    {
      "@type": "Person",
      "@id": PERSON_ID,
      name: ELIJAH.name,
      url: PROFILE_URL,
      jobTitle: ELIJAH.role,
    },
    {
      "@type": "WebPage",
      "@id": `${SITE_URL}/#webpage`,
      url: SITE_URL,
      name: PAGE_TITLE,
      description: ELIJAH.metadataDescription,
      isPartOf: { "@id": WEBSITE_ID },
      about: { "@id": PERSON_ID },
    },
  ],
};

// The OG image itself is generated by web/src/app/opengraph-image.tsx (the
// Next file convention), which Next automatically wires into og:image and
// twitter:image — no need to list it here.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: PAGE_TITLE,
  description: ELIJAH.metadataDescription,
  applicationName: ELIJAH.osName,
  authors: [{ name: ELIJAH.name, url: PROFILE_URL }],
  creator: ELIJAH.name,
  publisher: ELIJAH.name,
  alternates: { canonical: "/" },
  ...(SITE_VERIFICATION ? { verification: SITE_VERIFICATION } : {}),
  manifest: "/manifest.webmanifest",
  // favicon.ico is auto-wired by the src/app/favicon.ico file convention; these
  // add the PNG + apple-touch icons generated by `npm run build:icons`.
  icons: {
    icon: [
      { url: "/icon-192.png", type: "image/png", sizes: "192x192" },
      { url: "/icon-512.png", type: "image/png", sizes: "512x512" },
    ],
    apple: [{ url: "/apple-icon.png", sizes: "180x180" }],
  },
  appleWebApp: {
    capable: true,
    title: ELIJAH.osName,
    statusBarStyle: "black-translucent",
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: ELIJAH.osName,
    locale: "en_US",
    title: PAGE_TITLE,
    description: ELIJAH.metadataDescription,
  },
  twitter: {
    card: "summary_large_image",
    title: PAGE_TITLE,
    description: ELIJAH.metadataDescription,
  },
};

// Mobile shell relies on the visual viewport matching device width and on
// safe-area insets surviving full-bleed layout. `viewport-fit=cover` opts the
// page into the notch / home-indicator inset envelope on iOS.
//
// `interactive-widget=resizes-content` makes Android Chrome resize the LAYOUT
// viewport when the on-screen keyboard opens, so the shell's flex column
// simply shrinks and composers ride the keyboard with no script involved.
// (useKeyboardInset's --kb-inset math then computes ~0 and stays inert.)
// iOS Safari ignores the key — there, the visual-viewport tracking in
// useKeyboardInset carries the same job.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  interactiveWidget: "resizes-content",
  colorScheme: "dark",
  themeColor: THEME_COLORS.bgDeep,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={fontVariableClassName}
    >
      <body>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(SITE_JSON_LD).replace(/</g, "\\u003c"),
          }}
        />
        {children}
      </body>
    </html>
  );
}
